services:
  app_replica:
    image: cobperureiner/cyc_admin_67_app_replica:${VERSION}

    secrets:
      - source: admin_db_host_v2
        target: db_host

      - source: admin_db_user_v2
        target: db_user

      - source: admin_db_password_v2
        target: db_password

      - source: admin_db_name_v2
        target: db_name

      - source: admin_recaptcha_secret_key_v2
        target: recaptcha_secret_key

    deploy:
      replicas: 1

      restart_policy:
        condition: any

      update_config:
        order: start-first
        parallelism: 1
        delay: 2s

      rollback_config:
        order: stop-first
        parallelism: 1

    networks:
      - intranet_https_proxy

networks:
  intranet_https_proxy:
    external: true

secrets:
  admin_db_host_v2: { external: true }
  admin_db_user_v2: { external: true }
  admin_db_password_v2: { external: true }
  admin_db_name_v2: { external: true }

  admin_recaptcha_secret_key_v2:
    external: true
