services:
  app_replica:
    image: cobperureiner2/cyc_admin_67_app_replica:${VERSION}

    ports:
      - target: 80
        published: 5003
        protocol: tcp
        mode: ingress

    secrets:
      - source: db_host
        target: db_host

      - source: db_user
        target: db_user

      - source: db_password
        target: db_password

      - source: db_name
        target: db_name

    deploy:
      replicas: 1

      restart_policy:
        condition: any

      update_config:
        order: start-first
        parallelism: 1
        delay: 2s

      rollback_config:
        order: stop-first
        parallelism: 1

secrets:
  db_host:
    external: true

  db_user:
    external: true

  db_password:
    external: true

  db_name:
    external: true
